### ISSUE TITLE
Plugin doesn't recognize type definitions

### ISSUE THREAD

**Issue by siberian-man** [gabrielcolson/intellij-prisma#2]
The following code is considered as valid by prisma commands:

```
type ID = String @default(cuid()) @id
```

but this plugin marks it as invalid.

Actually, I don't see anything about type definitions in [PSL](https://github.com/prisma/specs/tree/master/schema) spec. 
But it's supported at least by Prisma 2.0.0-beta.4.

**Comment by gabrielcolson** [comment]
I followed the specs when I implemented the parser and I didn't even know this was possible. I am going to add this to the grammar. Thanks for pointing it!

**Comment by gabrielcolson** [comment]
@siberian-man could you provide an example `schema.prisma` that uses the type aliases?

**Comment by siberian-man** [comment]
Of course:

```prisma
type ID = String @default(cuid()) @id

model User {
  id                            ID
  nickname                      String?         @unique
  contacts                      Contact[]
  name                          String?
  password                      String?
  birthdate                     DateTime?
}
```

**Comment by gabrielcolson** [comment]
@siberian-man Hey! It was fixed by [this PR](https://github.com/gabrielcolson/intellij-prisma/pull/3). It will be part of the next release ;)

**Comment by siberian-man** [comment]
> @siberian-man Hey! It was fixed by [this PR](https://github.com/gabrielcolson/intellij-prisma/pull/3). It will be part of the next release ;)

What is your release schedule?

**Comment by gabrielcolson** [comment]
Hey @siberian-man! `1.2.0` has been pushed to JetBrains repositories. It will be released in a couple of days after they approve it.

**Comment by siberian-man** [comment]
Great! Thanks 😊

**Comment by siberian-man** [comment]
After plugin update I got this issue:

![image](https://user-images.githubusercontent.com/12710889/82444269-2b152280-9acd-11ea-80fa-727d4d7b4fd5.png)
