### ISSUE TITLE
Support cmd + / shortcut for commenting code

### ISSUE THREAD

**Issue by beeman** [gabrielcolson/intellij-prisma#5]
Thanks a lot for the plugin, it's great to be able to edit the schema's directly in WebStorm!

It would be great if you could support the shortcut for commenting code <kbd>cmd</kbd> + <kbd>/</kbd>, so we can do this:

![comment-code](https://user-images.githubusercontent.com/36491/81558001-89fecd00-9352-11ea-9c36-f26d3b204303.gif)

**Comment by gabrielcolson** [comment]
Thanks for the feedback! I will take a look this week!

**Comment by gabrielcolson** [comment]
Hey @beeman! Your feature was added by [this PR](https://github.com/gabrielcolson/intellij-prisma/pull/6) and will be part of the next release :)

**Comment by beeman** [comment]
Awesome @gabrielcolson, thanks a lot! Looking forward to try it!
