### ISSUE TITLE
Column named "type" shown as error

### ISSUE THREAD

**Issue by ghidoras** [gabrielcolson/intellij-prisma#9]
First of all thanks for your effort :) 

I have a model as follows:
```
model ReportComment {
    id String @id @default(cuid())

    body String

    report Report @relation(fields: [reportId], references: [id])
    reportId String

    type String // "GENERAL_FEEDBACK" | "PRIVATE_COMMENT"
    visibleByActorType String // "ALL" | "EDITOR" | "REVIEWER"

    createdAt DateTime @default(now())
    updatedAt DateTime @default(now())
}
```

and the column `type` is highlighted as an error:
<img width="793" alt="Screenshot 2020-05-23 at 12 34 12" src="https://user-images.githubusercontent.com/49431344/82728615-bbcc4800-9cf1-11ea-9081-4239bb670f91.png">

The issue was not there before updating to latest version.

**Comment by gabrielcolson** [comment]
Thanks for letting me know. I will fix this ASAP

**Comment by steebchen** [comment]
I also have this issue; it's a bit annoying because it's a hard error in IJ and most of the other syntax highlighting will fail with this error.

**Comment by gabrielcolson** [comment]
Hey @steebchen
I didn't have time to work on this recently but I will do it this week for sure.

**Comment by Denu8thell** [comment]
@gabrielcolson - I've been annoyed by this issue for a few day now, so I went ahead and tried to have a go at fixing this myself; I've submitted a pull request, feel free to review when you get the chance!

**Comment by gabrielcolson** [comment]
Hey, @Denu8thell thanks for the fix! I thought this issue would be solved by using the official [Prisma Language Server](https://github.com/prisma/vscode/tree/master/packages/language-server) (see #10), but it was harder than I thought and I didn't find any trivial way of doing it.

Anyway now it's fixed thanks to you! I will submit a new release to JetBrains today :D
